Feat 1.0.0 beta6
acquiredcom/acquired-payments-magento pull request #9
Opened 2024-08-22 11:28 UTC by stefane2buy1click

- Add unit tests for better code maintainance

2024-10-02 12:17 UTC, adamcox-acquired requested changes

2024-10-02 16:58 UTC, stefane2buy1click commented on Test/Unit/Gateway/Request/CardRefundBuilderTest.php
> +    private function getPaymentMock(float $amount, $transactionId): PaymentDataObjectInterface
I will extract this / refactor maybe in a shared abstract class extended by these test cases

2024-10-09 11:03 UTC, stefane2buy1click commented on Test/Unit/Gateway/Request/CardRefundBuilderTest.php
> +    private function getPaymentMock(float $amount, $transactionId): PaymentDataObjectInterface
@adamcox-acquired please check the payment mock setup simplification in the latest commit

2024-10-10 09:48 UTC, adamcox-acquired approved these changes

2024-10-17 12:25 UTC, stefane2buy1click commented
@adamcox-acquired resolved conflicts, please merge

2024-10-17 13:17 UTC, merged